transferwise/openbanking-client

CHANGELOG.md, CODEOWNERS, README.md, build.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/ApplicationType.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/ClientRegistrationRequest.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/ClientRegistrationResponse.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/RegistrationPermission.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/main/java/com/transferwise/openbanking/client/configuration/TppConfiguration.java, src/main/java/com/transferwise/openbanking/client/jwt/JwtClaimsSigner.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GrantType.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/ResponseType.java, src/main/java/com/transferwise/openbanking/client/security/KeySupplier.java, src/test/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestServiceTest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java, src/test/java/com/transferwise/openbanking/client/jwt/JwtClaimsSignerTest.java, src/test/java/com/transferwise/openbanking/client/test/TestAspspDetails.java, src/test/java/com/transferwise/openbanking/client/test/TestKeyUtils.java
The current dynamic client registration functionality is pretty limited, there is no functionality for building the registration request (a big part of the client registration logic) and the client class takes a raw string as the request body to send to the ASPSP, as well as returning the response body as a raw string.
This PR improves the situation by providing more functionality that TPPs need to implement dynamic client registration. The functionality is essentially copied from pisp-service but with a few tweaks to make it more configurable for different TPP use cases. 
Expand the dynamic client registration functionality, providing new functionality for building the registration request to send to the ASPSP, and changing the client to return the registration response as a full data …
=> Expand Registration Functionality (PAYINP-687)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/payment/common/AuthorizationContext.java, src/main/java/com/transferwise/openbanking/client/api/payment/common/BasePaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/PaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/main/java/com/transferwise/openbanking/client/configuration/TppConfiguration.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GetAccessTokenRequest.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/ResponseType.java, src/test/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClientTest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestServiceTest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java
We need to update our client registrations with ASPSPs to add a new TPP redirect URL. There is an optional API in the Open Banking standard to do this, that some ASPSPs support.
https://openbankinguk.github.io/dcr-docs-pub/v3.2/dynamic-client-registration.html
To allow the above registration update, this PR adds support for calling the update client registration API, and support for generating a registration request with multiple TPP redirect URLs in it. Each individual commit contains further details on the change.
=> Updating Client Registrations (PAYINP-779)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GetAccessTokenRequest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java
Certain ASPSPs reject requests to get an access token, when no scope parameter is specified in the request. This causes attempts to update a client registration to fail. 
When getting an access token prior to calling the update client registration endpoint, specify a scope of `openid` in the access token request.
While the registration specification states it's not strictly required, some ASPSPs require the scope parameter to be present in the access token request. As this access token won't be used for the accounts or payments API, we can use the `openid` scope to avoid having to worry about what permission the TPP already has and using that.
=> Update Registration Operation (PAYINP-777)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java
Certain ASPSPs reject requests to get an access token, when a scope of `openid` is specified in the request. This causes attempts to update a client registration to fail.
When getting an access token prior to calling the update client registration endpoint, specify a scope of `payments` in the access token request.
Some ASPSPs do not support requesting a scope of only `openid`, using `payments` instead should be fine for now instead and allow the update client registration operation to succeed for these ASPSPs.
=> Payinp 777 update registration scope

src/main/java/com/transferwise/openbanking/client/api/payment/v3/PaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/configuration/SoftwareStatementDetails.java, src/main/java/com/transferwise/openbanking/client/jwt/JwtClaimsSigner.java, src/test/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClientTest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestServiceTest.java, src/test/java/com/transferwise/openbanking/client/jwt/JwtClaimsSignerTest.java
Make it easier for the client library to work with multiple software statements at the same time, without having to go through extra hoops of creating separate instances of classes per software statement. 
Refactor the classes which use the `TppConfiguration` class as a class variable, to instead take an instance of the class as a method parameter.
This makes it easier to have multiple `TppConfiguration` in use at the same time, without having to create separate instances of the classes which use it.
Also rename the `TppConfiguration` class to `SoftwareStatementDetails` to better describe what the class now represents, i.e. the details of the software statement to use for the ASPSP integration.
=> Multiple Software Statement Support (PAYINP-817)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/ClientRegistrationResponse.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java, src/test/java/com/transferwise/openbanking/client/test/TestAspspDetails.java
As we've started making use of the update client registration API endpoint, we've discovered two quirks in ASPSP implementations, this PR allows this library to gracefully handle them. 
See individual commits for details.
=> Registration fixes

src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/main/java/com/transferwise/openbanking/client/oauth/PrivateKeyJwtAuthentication.java, src/test/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClientTest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestServiceTest.java, src/test/java/com/transferwise/openbanking/client/oauth/PrivateKeyJwtAuthenticationTest.java, src/test/java/com/transferwise/openbanking/client/test/TestAspspDetails.java
Certain ASPSPs require a non-standard `iss` value to be provided in the registration request, as opposed to the standard value of the 'software statement ID', therefore it would be nice if the value to use could be easily customised via the `AspspDetails` interface (where we customise other behaviour).  
While adding this functionality I also felt that several other methods in the `AspspDetails` interface had slightly unclear / confusing names, and could have better default values where there is a clear standard value to use. 
Note, I haven't bumped up the changelog or version in this PR as I plan to roll these changes into the release notes for https://github.com/transferwise/openbanking-client/pull/8
See individual commits for details.
=> Aspsp Details Interface Refactoring

CHANGELOG.md, README.md, build.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/payment/common/BasePaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/PaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/json/JacksonJsonConverter.java, src/main/java/com/transferwise/openbanking/client/json/JsonConverter.java, src/main/java/com/transferwise/openbanking/client/jwt/JwtClaimsSigner.java, src/test/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClientTest.java, src/test/java/com/transferwise/openbanking/client/json/JacksonJsonConverterTest.java, src/test/java/com/transferwise/openbanking/client/jwt/JwtClaimsSignerTest.java
Certain ASPSPs reject create payment consent and create payment requests when using the latest version of this library, because null fields in the requests are included in the serialised JSON values.  
Introduce a new `JsonConverter` interface with a default implementation using the Jackson library, and use this for converting objects to JSON strings in the JWT claims signer and v3 REST payment client.
This is done to ensure that when serialising objects to JSON, null fields are not included in the serialised JSON, as some ASPSPs do not handle (ignore) null fields and reject requests containing these.
This was previously done by having the Jackson `@JsonInclude(JsonInclude.Include.NON_EMPTY)` annotation on the v3 payment domain classes, but the new generated model classes don't have these …
=> JSON Serialisation

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/json/JacksonJsonConverter.java, src/main/java/com/transferwise/openbanking/client/json/JsonConverter.java, src/main/java/com/transferwise/openbanking/client/json/JsonReadException.java, src/main/java/com/transferwise/openbanking/client/json/JsonWriteException.java, src/test/java/com/transferwise/openbanking/client/json/JacksonJsonConverterTest.java
For some ASPSPs we are seeing JSON de-serialization exceptions when calling their confirmation of funds API, unfortunately the (Jackson) exception raised does not contain enough information to understand how the JSON is invalid.
A snippet of an example stack trace is given below to highlight this. 
```
Caused by: org.springframework.web.client.RestClientException: Error while extracting response for type [class com.transferwise.openbanking.client.api.payment.v3.model.OBWriteFundsConfirmationResponse1] and content type [application/json;charset=UTF-8]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token; nested exception is …
```
=> Payment API Response JSON Handling (PAYINP-951)

CHANGELOG.md, build.gradle, gradle.properties, specs/payment-initiation-v3-swagger.yaml, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GetAccessTokenRequest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java, src/test/java/com/transferwise/openbanking/client/test/TestAspspDetails.java
This release includes two main changes, I've rolled them into one single PR as the individual changes are fairly small and it avoids doing multiple releases, one right after another. 
With the previous [PR](https://github.com/transferwise/openbanking-client/pull/32) we can now see exactly why we were getting that Jackson processing exception. The issue relates to how we have changed the type of the `OBSupplementaryData1` in the Open Banking model definition from an object type to a string type. 
To support Nationwide's recent changes to their client registration API, we need to support more customisation of the following behaviour when updating a client registration. 
- The scope of the access token requested for the authenticated call to the registration API
- The transport certificate …
=> Supplementary Data Model Field (PAYINP-951) & Client Registration Customisation (PAYINP-952)

src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationRequestService.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/domain/ErrorResponse.java, src/main/java/com/transferwise/openbanking/client/oauth/ScopeFormatter.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GetAccessTokenRequest.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java, src/test/java/com/transferwise/openbanking/client/oauth/ScopeFormatterTest.java
Continuing with the work to provide callers with easy access to structured error responses, doing the same refactoring as was done for the payments client, to the registration client. 
Refactor the registration client so that the OAuth access token to use for the update client registration API call to the ASPSP, is passed in by the caller rather than being fetched by the registration client internally.
Further refactor the registration client implementation so that when the API call fails because the ASPSP returned a non-successful response, we return a response wrapper that signals the call failed, rather than throwing an exception. This failure response wrapper contains the details of the response, the failure, and the parsed structured error response.
Also with the registration client …
=> Registration Client Refactoring (PAYINP-962)

src/main/java/com/transferwise/openbanking/client/oauth/OAuthClient.java, src/main/java/com/transferwise/openbanking/client/oauth/RestOAuthClient.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/ErrorResponse.java, src/test/java/com/transferwise/openbanking/client/oauth/RestOAuthClientTest.java
Continuing with the work to provide callers with easy access to structured error responses, doing the same refactoring as was done for the payments client, to the OAuth client.
Refactor the OAuth client implementation so that when the API call fails because the ASPSP returned a non-successful response, we return a response wrapper that signals the call failed, rather than throwing an exception. This failure response wrapper contains the details of the response, the failure, and the parsed structured error response.
This follows the same refactoring done for the payment client, to give callers easy access to the parsed structured error response on API call failure.
=> OAuth Client Refactoring (PAYINP-962)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/registration/RegistrationClient.java, src/main/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClient.java, src/test/java/com/transferwise/openbanking/client/api/registration/RestRegistrationClientTest.java
We need to call the delete client registration API for certain banks. 
Extend the registration client to include support for calling the 'delete client registration' endpoint.
As we'll want to make use of this change right away, also update the changelog and version number so a new version can be published.
=> Delete Registration Endpoint (PAYINP-1080)

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/VrpClient.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
Use client_credential grant type for initiating the vrp payment.  
remove authentication context from vrp client payment initiation method.
=> UKGROWTH-55 Use client_credenial grantype for domestic vrp payments

CHANGELOG.md, README.md, build.gradle, build.publishing.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/common/BasePaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/VrpClient.java, src/main/java/com/transferwise/openbanking/client/oauth/RestOAuthClient.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/AccessTokenResponse.java, src/main/java/com/transferwise/openbanking/client/oauth/domain/GetAccessTokenRequest.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
To implement VRP we need to have a possibility to exchange `code` to `access_token` and `refresh_token`. And also exchange `refresh_token` for valid `access_token`.  
- Add `refresh_token` to `com.transferwise.openbanking.client.oauth.domain.AccessTokenResponse` so it can be used to get valid access token
- Add `BasePaymentClient.exchangeRefreshToken` method that can exchange refresh_token to access_token and refresh_token
- Change method signature for `BasePaymentClient.exchangeAuthorizationCode` to return `AccessTokenResponse` and make it public
=> Update BasePaymentClient to support exchange of code and refresh_token for access_token

CHANGELOG.md, build.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/common/BasePaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
As mentioned in [OB Known Specification Issues v319_KI15](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/47546479/Known+Specification+Issues) resource group of VRP endpoints will be changed from existing VRP resource group to PISP. But some banks still have VRP so adding a default method to `AspspDetails` that can be overrided.
- Add default `AspspDetails.getVrpBaseResourceName()` method to support dynamic resource name for VRP
- Upgrade `com.diffplug.spotless` to `6.4.2`
- Upgrade `io.swagger.codegen.v3:swagger-codegen-cli` to `3.0.34`
- Upgrade `org.bitbucket.b_c:jose4j` to `0.7.11`
- Upgrade `ch.qos.logback:logback-classic` to `1.2.11`
=> Add default  method to support dynamic resource name for VRP

CHANGELOG.md, build.gradle, gradle.properties, specs/vrp-openapi.yaml
VRP 3.1.9 specification is [now live](https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/vrp-openapi.yaml) so we need to upgrade it 
- Upgrade `com.diffplug.spotless` to `v6.5.1`
- Upgrade `org.bitbucket.b_c:jose4j` to `0.7.12`
=> Update `specs/vrp-openapi.yaml` with VRP 3.1.9 specification

CHANGELOG.md, gradle.properties, specs/vrp-openapi.yaml, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
`OBDomesticVRPConsentResponseData.debtorAccount` has type `Object` where it should be `OBCashAccountDebtorWithName`.
As Yes and No are reserved in openapi they automatically transforms to True and False. Adding quotes.
- Update `specs/vrp-opeapi.yaml` so that debtorAccount field has OBCashAccountDebtorWithName type
and ReadRefundAccount has "YES" and "NO" enum values
=> Update  so that debtorAccount field has OBCashAccountDebtorWithName type

CHANGELOG.md, build.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/payment/v3/PaymentApiCallException.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/PaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/VrpApiCallException.java, src/main/java/com/transferwise/openbanking/client/api/vrp/VrpClient.java, src/test/java/com/transferwise/openbanking/client/api/payment/v3/RestPaymentClientTest.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
The problem is openbanking-client returning ApiCallException with response body. Would be good to have it parsed to `OBErrorResponse1`.
- Extend existing ApiCallException class with two implementations: PaymentApiCallException and VrpApiCallException.
New error classes may contain additional information about an error such as response code, Open Banking response error
code and a bank error description.
- Upgrade com.diffplug.spotless to v6.8.0
- Upgrade com.github.spotbugs to v5.0.9
=> Extend existing ApiCallException class with two implementations: PaymentApiCallException and VrpApiCallException [UKGRO-235]

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
Make `getFundsConfirmation` function in `RestVrpClient` call the external endpoint with a `POST` method instead of `GET` as it is a `POST` method according to [open banking standards](https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/vrp/domestic-vrp-consents.html#post-domestic-vrp-consentsconsentidfunds-confirmation)
=> [UKGRO-247] [Bugfix] make getFundsConfirmation for RestVrpClient a POST endpoint

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/common/OpenBankingHeaders.java, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/VrpClient.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
Fix headers for getFundsConfirmationRequest in VrpRestClient
Earlier vs Now
headers 
1. Took client credentials as AUTH
2. JWS was not signed
Now
1. Takes access token provided by the client as AUTH
2. JWS is signed
Note - No idempotency header is needed for this POST request
Reference -[ link (look at the endpoints table)](https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/vrp/domestic-vrp-consents.html)
=> [UKGRO-247] Fix headers for getFundsConfirmationRequest in VrpRestClient

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java, src/main/java/com/transferwise/openbanking/client/json/JacksonJsonConverter.java, src/main/java/com/transferwise/openbanking/client/json/VrpConsentResponseStatusEnumDeserializer.java, src/test/java/com/transferwise/openbanking/client/api/vrp/RestVrpClientTest.java
Openbaking doesn't support 'Revoked' StatusEnum from 3.1.8, but banks are still sending Revoked status.
This error should not impact customer and, we have decided to treat Revoked as Rejected. 
1. The best way to handle this error is when the response is returned from bank. 
2. I am replacing Revoked string with rejected in response body. To avoid any unwanted changes, I am prefixing search string with status like “Status”:”Revoked”. 
3. Moved the above handling to separate function to have cleaner and follow single responsibility principle. 
4. I have explored other solutions like customizing JSON converter to handle not present enum but didn't find any.
=> [EUPAY-368] Fix  GetConsent failures when bank send Revoked status enum.

CHANGELOG.md, build.gradle, gradle.properties, specs/event-notifications-openapi.json, specs/event-notifications-openapi.yaml
To support of /event-notification callback in a client which will be called by bank to send VRP consent revocation notification. 
The payload class of Event Notification (OBEventNotification1)  is generated through this spec. 
I am putting this spec here as all other specs of open banking are here. 
Bumping version to 13.0.0 
1. Added spec from https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/event-notifications-openapi.yaml
2. Updated the build.gradle file to add swagger configuration for above spec.
=> [EUPAY-453] Adding  /event-notifications-openapi.yaml spec

CHANGELOG.md, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/event/EventClient.java, src/main/java/com/transferwise/openbanking/client/api/event/RestEventClient.java, src/test/java/com/transferwise/openbanking/client/api/event/RestEventClientTest.java
Renaming Event client APIs to reflect the event subscription resource:
Currently, the name informs that we are subscribing to just one event, but there can be multiple event in a request. 
Open banking spec these are called Event Subscription. 
`subscribeToAnEvent` changed to `createEventSubscription`, 
`getAllEventResources` changed to `getEventSubscriptions`, `changeAnEventResource` changed to `changeEventSubscription`, `deleteAnEventResource` changed to `deleteEventSubscription`
=> [EUPAY-546] Renaming Event client APIs to reflect event subscription resource

CHANGELOG.md, gradle.properties, specs/event-notifications-openapi.yaml
There is discrepancy in open banking event notification documentation https://openbankinguk.github.io/read-write-api-site3/v3.1.10/resources-and-data-models/event-notifications/event-notifications.html
They have used OBEventNotification1 as request body in some place and OBEventNotification2 some place else. 
Their spec https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/event-notifications-openapi.yaml doesn't contains OBEventConsentAuthorizationRevoked1 & OBEventAccountAccessConsentLinkedAccountUpdate1 schema. 
I have searched google and people are customising spec if openbanking spec is not correct. 
Tested locally in PISP service.  Able to parse consent revoked notification. 
- Created our own custom schema for OBEventConsentAuthorizationRevoked1 and …
=> [EUPAY-580] Updating event-notifications-openapi.yaml with OBEventConsentAuthorizationRevoked1 schema

CHANGELOG.md, gradle.properties, specs/vrp-openapi.yaml
Santander have emailed to let us know they will not support versions  v3.1.9 of the Open Banking spec. Our current PISP version is based from v3.1.9.
Picked up the 3.1.10 VRP spec from https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/vrp-openapi.yaml. 
We custom override: 
1. x-numerated-enum is changed to enum. 
2. double quote is added to Yes keyword. 
https://transferwise.atlassian.net/wiki/spaces/EUP/pages/2893801433/Open+banking+VRP+Migration+Assessment+From+version+3.1.9+to+3.1.10
=> [EUPAY-726]VRP Migration: From version 3.1.9 to 3.1.10

.github/workflows/pr-checks.yml, CHANGELOG.md, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/transferwise/openbanking/client/configuration/AspspDetails.java, src/test/java/com/transferwise/openbanking/client/api/event/RestEventClientTest.java
Java version not updated for long time and official Java version is also 17
It makes difficult for developer to build on old version. 
1. Update Java version to 17. 
2. Gradle to 7.6 as 7.0 was not compatible to Java 17. 
3. Some checkstyle and test was failing due to syntax change in new Java. Fixed those.
=> [EUPAY-727] Upgrading Java to 17 and gradle to 7.6

CHANGELOG.md, build.gradle, gradle.properties, src/main/java/com/transferwise/openbanking/client/api/event/RestEventClient.java, src/main/java/com/transferwise/openbanking/client/api/vrp/RestVrpClient.java
Going forward we want openbanking-client to support Spring Boot 3.  To do this we need to make use of Spring Web 6 which is the current version of Spring within Spring Boot 3. 
This brings in the latest version of Spring Web (and Jackson) and makes a small modification to the code to support the new interfaces. 
Going forward, this library will not support earlier versions of Spring Web
=> EUPAY-957: Move openbanking-client to Spring Web 6.

CHANGELOG.md, gradle.properties, specs/vrp-openapi.yaml
Mandatory,  spec upgrade is required by HSBC, otherwise we won't be able to provide HSBC integration in openbanking. 
Picked up the 3.1.11 VRP spec from https://github.com/OpenBankingUK/read-write-api-specs/blob/master/dist/openapi/vrp-openapi.yaml.
**Custom override:**
x-numerated-enum is changed to enum.
double quote is added to Yes keyword.
allOf: which do validation, is not removed. 
All changes, without customisation, can be seen here: https://github.com/transferwise/openbanking-client/pull/225/files?diff=split&w=1
=> [EUPAY-1033] VRP Spec Upgrade: From version 3.1.1 to 3.1.11
